"exceptions.py - define schema exceptions"

class DuplicateName(ValueError):
    """duplicate name"""
    pass

